### ISSUE TITLE
Looping info table

### ISSUE THREAD

**Issue by ArcadeTV** [ArcadeTV/msu-md-shinobi2#1]
I have no clue which track shall loop and which not.
Please let me know here. Tracklist for reference:

**SoundID**|**Track Title**|**Track No.**|**loop**
:-----:|:-----:|:-----:|:-----:
$81|The Shinobi|1|yes
$82|Terrible Beat|2|yes
$83|Round Clear|3|no
$84|Make Me Dance|4|yes
$85|Over the Bay|5|yes
$86|China Town|6|yes
$87|Run or Die|7|yes
$88|Like a Wind|8|yes
$89|Labyrinth|9|yes
$8A|Sunrise Blvd.|10|yes
$8B|The Dark City|11|yes
$8C|Ninja Step|12|yes
$8D|Long Distance (story)|13|yes
$8E|Failure|14|no
$8F|Silence Night|15|no
$90|My Lover|16|yes
$91|Game Over|17|no
$92|The Ninja Master|18|yes
$93|Opening|19|no

**Comment by ArcadeTV** [comment]
Original Message from @Macck18

Song name = game position

Opening = first demorun

Failure = gameover

Long distance = history introduction (if not press start)

The Shinobi = stage 1A
Stage Clear
The Shinobi = stage 1B
Stage Clear
Terrible Beat = boss fight
Stage Clear


Sunrise BLVD = stage 2A
Stage Clear
Make me Dance = 2B
Stage Clear
Terrible Beat = boss fight
Stage Clear


Like a Wind = stage 3A
Stage Clear
Run or Die = stage 3B
Stage Clear
Terrible Beat = boss fight
Stage Clear


Like a Wind = stage 4A
Stage Clear
Ninja Step = stage 4B
Stage Clear
Terrible Beat = boss fight
Stage Clear


The Dark City = stage 5A
Stage Clear
Sunrise BLVD = stage 5B
Stage Clear
Terrible Beat = boss fight
Stage Clear


ChinaTown = stage 6A
Stage Clear
Run or Die = stage 6B
Stage Clear
Terrible Beat = boss fight
Stage Clear


Over the bay = stage 7A
Stage Clear
Ninha Step = stage 7B
Stage Clear
Terrible Beat = boss fight
Stage Clear


Over the bay = stage 8A
Stage Clear
Labyrinth = stage 8B
Stage Clear

The Ninja Master = last boss fight

My lover = good ending

Silence night = bad ending

**Comment by ArcadeTV** [comment]
> Failure = gameover

are you sure this is correct? I checked against [project2612](https://project2612.org/details.php?id=135) and **failure** seems like the dying sound, while **game over** is game over.

So, all "Stages" music tracks are looping?

You can quote my table in the first post and fill it for extra reference.

**Comment by ArcadeTV** [comment]
I found this in the vgm archive of "Revenge of Shinobi"

```
Name                                Length:
                                    Total  Loop
Opening                             0:19   -
Long Distance                       0:20   0:19
The Shinobi                         0:51   0:51
Terrible Beat                       0:22   0:19
Round Clear                         0:02   -
Sunrise Blvd.                       1:47   1:42
Make Me Dance                       0:58   0:53
Like a Wind                         0:45   0:37
Run or Die                          0:28   0:26
Ninja Step                          1:01   0:38
The Dark City                       0:34   0:29
China Town                          1:15   1:15
Over the Bay                        0:45   0:45
Labyrinth                           0:12   0:12
The Ninja Master                    1:06   0:33
Failure                             0:03   -
My Lover                            1:03   1:03
Silence Night                       0:43   -
Game Over                           0:07   -
```

**Comment by Macck18** [comment]
> Yes you are right, failure it's a dying sound.

Your table is almost right, only add that the ROUND CLEAR does not loop. I think "My lover" and "Silence Night" does not loop to.
> 
> I have no clue which track shall loop and which not.
> Please let me know here. Tracklist for reference:
> **SoundID** 	**Track Title** 	**Track No.** 	**loop**
> $81 	The Shinobi 	1 	
> $82 	Terrible Beat 	2 	
> $83 	Round Clear 	3 	NO
> $84 	Make Me Dance 	4 	
> $85 	Over the Bay 	5 	
> $86 	China Town 	6 	
> $87 	Run or Die 	7 	
> $88 	Like a Wind 	8 	
> $89 	Labyrinth 	9 	
> $8A 	Sunrise Blvd. 	10 	
> $8B 	The Dark City 	11 	
> $8C 	Ninja Step 	12 	
> $8D 	Long Distance (story) 	13 	
> $8E 	Failure 	14 	no
> $8F 	Silence Night 	15 	
> $90 	My Lover 	16 	
> $91 	Game Over 	17 	no
> $92 	The Ninja Master 	18 	
> $93 	Opening 	19 	no

**Comment by ArcadeTV** [comment]
Great, thanks! 
I have updated the source and will release an updated version.
Hope you like it!?
