### ISSUE TITLE
Song position

### ISSUE THREAD

**Issue by Macck18** [ArcadeTV/msu-md-shinobi2#3]
Song name = game position

Opening = first demorun

Failure = gameover

Long distance = history introduction (if not press start)

The Shinobi = stage 1A
Stage Clear
The Shinobi = stage 1B
Stage Clear
Terrible Beat = boss fight
Stage Clear

Sunrise BLVD = stage 2A
Stage Clear
Make me Dance = 2B
Stage Clear
Terrible Beat = boss fight
Stage Clear

Like a Wind = stage 3A
Stage Clear
Run or Die = stage 3B
Stage Clear
Terrible Beat = boss fight
Stage Clear

Like a Wind = stage 4A
Stage Clear
Ninja Step = stage 4B
Stage Clear
Terrible Beat = boss fight
Stage Clear

The Dark City = stage 5A
Stage Clear
Sunrise BLVD = stage 5B
Stage Clear
Terrible Beat = boss fight
Stage Clear

ChinaTown = stage 6A
Stage Clear
Run or Die = stage 6B
Stage Clear
Terrible Beat = boss fight
Stage Clear

Over the bay = stage 7A
Stage Clear
Ninha Step = stage 7B
Stage Clear
Terrible Beat = boss fight
Stage Clear

Over the bay = stage 8A
Stage Clear
Labyrinth = stage 8B
Stage Clear

The Ninja Master = last boss fight

My lover = good ending

Silence night = bad ending

**Comment by ArcadeTV** [comment]
> Failure = gameover

are you sure this is correct? I checked against [project2612](https://project2612.org/details.php?id=135) and **failure** seems like the dying sound, while **game over** is game over.

Also i will close this and merge it here:
https://github.com/ArcadeTV/msu-md-shinobi2/issues/1
