### ISSUE TITLE
After defeat the last boss

### ISSUE THREAD

**Issue by Macck18** [ArcadeTV/msu-md-shinobi2#5]
**Patch version**
Yes

**Platform**
Genesis VA3 with Mega SD

**Describe the bug**
After defeating the last boss, in the "the end scene" the game plays the opening music (not the my lover theme)... and after that goes silent. I don't know if this is a Mega SD bug or the rom.

**Comment by ArcadeTV** [comment]
It's actually both :-/
I just fixed the ending music, i can confirm for "Silent Night" (because I'm too lame to save the chick in time)
v.1.1 is on the way...
